/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Cake.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/models/Cake.glb')
	return (
		<group ref={group} {...props} dispose={null} >
			<mesh geometry={nodes['Circle006-Mesh'].geometry} castShadow receiveShadow material={materials.F06292} />
			<mesh geometry={nodes['Circle006-Mesh_1'].geometry} castShadow receiveShadow material={materials.FFFFFF} />
			<mesh geometry={nodes['Circle006-Mesh_2'].geometry} castShadow receiveShadow material={materials['039BE5']} />
		</group>
	)
}

useGLTF.preload('/models/Cake.glb')